import {estado} from './estado';

export const ESTADOS: estado[] =[
   {id:1 , nombre:'Amazonas', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} , 
   {id:2 , nombre:'Anzoategui', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:3 , nombre:'Apure', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} , 
   {id:4 , nombre:'Aragua', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:5 , nombre:'Barinas', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:6 , nombre:'Bolívar', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:7 , nombre:'Carabobo', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:8 , nombre:'Cojedes', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:9 , nombre:'Delta Amacuro', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:10 , nombre:'Distrito Capital', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:11 , nombre:'Falcón', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:12 , nombre:'Guárico', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:13 , nombre:'Lara', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:14 , nombre:'Mérida', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:15 , nombre:'Miranda', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:16 , nombre:'Monagas', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:17 , nombre:'Nueva Esparta', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:18 , nombre:'Portuguesa', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:19 , nombre:'Sucre', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:20 , nombre:'Táchira', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:21 , nombre:'Trujillo', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:22 , nombre:'Vargas', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:23, nombre:'Yaracuy', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} ,
   {id:24, nombre:'Zulia', imagen:'4.png', gastronomia:'Entre sus platos tipicos se encuentran: Sopa de Ostras, Empanada de Salmón, Callos a la Gallega,Lomo de Merluza con Gambas, Mousse de Castaña, Chuletón de Ternera Gallego', cultura:'hola'} 
];